services:
  php:
    build: .
    container_name: studygroup-php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: studygroup-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studygroup_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql:ro

volumes:
  db_data:
