name: StudyGroup CI/CD - DB Sync

on:
  push:
    branches:
      - main  # Trigger on main branch push

jobs:
  sync-db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.LOCAL_MYSQL_PASSWORD }}
          MYSQL_DATABASE: studygroup_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL container
        run: sleep 20  # wait for container to be ready

      - name: Dump local Docker MySQL
        run: |
          docker exec $(docker ps -qf "name=mysql") \
          mysqldump -u root -p${{ secrets.LOCAL_MYSQL_PASSWORD }} studygroup_db > studygroup_db.sql

      - name: Import dump to Azure MySQL
        run: |
          mysql -h ${{ secrets.AZURE_MYSQL_HOST }} \
                -u ${{ secrets.AZURE_MYSQL_USER }} \
                -p${{ secrets.AZURE_MYSQL_PASSWORD }} \
                --ssl studygroup_db < studygroup_db.sql

      - name: Notify Success
        run: echo "Database successfully synced to Azure MySQL!"
